#!/bin/bash

if pgrep -x "compton" > /dev/null; 
then     echo "Running"; 
else     compton -b --config /usr/share/themes/Adapta-Maia/openbox-3/compton.conf;
fi &

notify-send "Desktop Loading" &
 
if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "gnome-games" > /dev/null; 
then     pkill gnome-games; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi  &

if pgrep -x "cairo-dock" > /dev/null; 
then     echo "Running"; 
else     cairo-dock -o;
fi &

if pgrep -x "msm_notifier" > /dev/null; 
then     echo "Running"; 
else     msm_notifier;
fi &

if pgrep -x "nm-applet" > /dev/null; 
then     echo "Running"; 
else     nm-applet;
fi &

if pgrep -x "pamac-tray" > /dev/null; 
then     echo "Running"; 
else     pamac-tray;
fi &

if pgrep -x "jade-dashboard" > /dev/null; 
then     echo "Running"; 
else     dex /usr/share/applications/jade-dashboard.desktop;
fi     
