#!/bin/bash

notify-send "Desktop Loading" &
 
if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     pkill $JADE_TERMINAL; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi  

if pgrep -x "jade-dashboard" > /dev/null; 
then     echo "Running"; 
else     /opt/jade/jade-dashboard && notify-send "Jade Ready";
fi     
