#!/bin/bash

notify-send "Kodi Mode Loading" &

#pkill jade-dashboard &

if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     pkill $JADE_TERMINAL; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     echo "Running"; 
else     kodi && notify-send "Kodi Mode Loaded";
fi
