#!/bin/bash

notify-send "Steam Mode Loading" &

#pkill jade-dashboard &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     pkill $JADE_TERMINAL; 
fi &

if pgrep -x "steam" > /dev/null; 
then     echo "Running"; 
else     steam -bigpicture;
fi
