#!/bin/bash

notify-send "Terminal Mode Loading" &

#pkill jade-dashboard &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi &

if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "jade-dashboard" > /dev/null; 
then     pkill jade-dashboard; 
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     echo "Running";
else     $JADE_TERMINAL && notify-send "Hyper Ready"; 
fi 

